apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
  labels:
    app: nginx
    owner: Baglai
spec:
  replicas: 2
  selector:
    matchLabels:
      project: nginx-app
  template:
    metadata:
      labels:
        project: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: lmellos/test-image
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-nginx-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-scaling
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70